RealTimeChat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('api/v1/', include('api.urls')),
]

api/urls.py
from django.urls import path

from rest_framework.routers import DefaultRouter

from .views import TopicViewset, UserViewset, MessageViewset, DelayedMessagesViewset

router = DefaultRouter()
router.register('topics', TopicViewset, basename='topics')
router.register('users', UserViewset, basename='users')
router.register('messages', MessageViewset, basename='messages')
router.register('delayedmessages', DelayedMessagesViewset, basename='delayedmessages')

urlpatterns = [
    
] + router.urls

chat/urls.py
from re import template
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import TopicView, MessageView, RegistrationView, DelayedMessageView

app_name = 'chat'
urlpatterns = [
    path('', TopicView.as_view(), name='topic'),
    path('<int:pk>/', MessageView.as_view(), name='room'),
    path('<int:pk>/delayedmeesage', DelayedMessageView.as_view(), name='delayedmessage'),
    path('login/', LoginView.as_view(template_name='chat/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
]

api/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models

from datetime import datetime


class Topic(models.Model):
    topic_name = models.CharField(max_length=50, verbose_name='Topic of discussion')

    def __str__(self):
        return self.topic_name

class Message(models.Model):
    topic_message = models.ForeignKey(Topic, on_delete=models.CASCADE)
    sender_name = models.CharField(max_length=50, verbose_name='Sender`s name')
    text = models.TextField(verbose_name='Text')
    date_time = models.DateTimeField(verbose_name='Date and time', default=datetime.now())
    anonymous = models.BooleanField(verbose_name='Anon', default=False)

    def __str__(self):
        return self.text

class DelayedMessages(Message, models.Model):
    pass

    def __str__(self):
        return self.text

chat/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import ModelForm

from .models import Topic

User = get_user_model()


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

api/views.py
from rest_framework import viewsets

from .serializers import TopicSerializer, MessageSerializer, UserSerializer, DelayedMessagesSerializer

from chat.models import Topic, Message, DelayedMessages

from django.contrib.auth import get_user_model

User = get_user_model()


class TopicViewset(viewsets.ModelViewSet):
    serializer_class = TopicSerializer
    queryset = Topic.objects.all()

class UserViewset(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()

class MessageViewset(viewsets.ModelViewSet):
    serializer_class = MessageSerializer
    queryset = Message.objects.all()

class DelayedMessagesViewset(viewsets.ModelViewSet):
    serializer_class = DelayedMessagesSerializer
    queryset = DelayedMessages.objects.all()

chat/views.py
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Topic, Message, DelayedMessages
from .forms import RegistrationForm

class TopicView(LoginRequiredMixin, CreateView):
    model = Topic
    login_url = 'chat:login'
    template_name = 'chat/index.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["topics"] = Topic.objects.order_by('-id')
        return context

    def get_success_url(self):
        success_url = reverse_lazy("chat:topic")
        return success_url

class MessageView(LoginRequiredMixin, ListView):
    login_url = 'chat:login'
    template_name = 'chat/room.html'
    context_object_name = 'messages'
    paginate_by = 5

    def get_queryset(self):
        return Message.objects.filter(topic_message__pk=self.kwargs['pk'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topic_id'] = self.kwargs['pk']
        return context

class RegistrationView(CreateView):
    form_class = RegistrationForm
    template_name = 'chat/registration.html'
    success_url = reverse_lazy('chat:login')

class DelayedMessageView(LoginRequiredMixin, CreateView):
    login_url = 'chat:login'
    model = DelayedMessages
    template_name = 'chat/delayedmessage.html'
    fields = ('text', 'date_time', 'anonymous')

    def form_valid(self, form):
        form.instance.topic_message_id = self.kwargs['pk']
        form.instance.sender_name = self.request.user.username
        return super().form_valid(form)
    
    def get_success_url(self):
        success_url = reverse_lazy("chat:room", args=(self.kwargs["pk"],))
        return success_url

chat/templates/chat/delayedmessage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DelayedMessage</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

</head>
<body>
    <div style="margin: 20px;">
        <form method="POST">
            {% csrf_token %}

            {{ form.as_p }}

            <input type="submit" value="Send" class="btn btn-success">
        </form>
    </div>
</body>
</html>

chat/templates/chat/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <title>Topics</title>
    
</head>
<body>
    <div style="margin: 20px;">
        <header>
            <div>
                <p>Hello, {{ user }} <span><a href="{% url 'chat:logout' %}" class="btn btn-danger">Exit</a></span></p>
            </div>
        </header>

        <div style="background-color: dimgray; width: 400px; padding: 20px; border-radius: 6px;">
            <p>Create a topic</p>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary">
            </form>
        </div>

        <p>What chat room would you like to enter?</p>
        <div> 
            {% for t in topics %}
                <a href="{% url 'chat:room' t.id %}?name={{ t.topic_name }}" style="background-color: rosybrown; width: 200px; height: 50px; display: inline-block; margin: 20px; color: white; border-radius: 6px;">{{ t.topic_name }}</a>
            {% endfor %}
        </div>
    </div>
</body>
</html>

chat/templates/chat/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
    <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
        <form method="POST" style="display: inline-block;">
            {% csrf_token %}
    
            {{ form.as_p }}
    
            <input type="submit" value="Sign in" class="btn btn-primary">
        </form>
        <div style="display: inline-block;">
            <a href="{% url 'chat:registration' %}"><input type="button" value="Sign up" class="btn btn-dark"></a>
        </div>
    </div>
</body>
</html>

chat/templates/chat/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
    <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
        <form method="POST" style="display: inline-block;">
            {% csrf_token %}
    
            {{ form.as_p }}
    
            <input type="submit" value="Sign up" class="btn btn-primary">
        </form>

        <div style="display: inline-block;">
            <a href="{% url 'chat:login' %}"><input type="button" value="Sign in" class="btn btn-dark"></a>
        </div>
    </div>
</body>
</html>

chat/templates/chat/room.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Room</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
    <div style="margin: 20px;">
        <h3>Topic: {{ request.GET.name }}</h3>

        <div id="chat_messages">
            {% for m in page_obj %}
                <div style="width: 450px; background-color: gray; margin: 20px;" class="number_div">
                    <div>
                        {% if not m.anonymous %}
                            {{ m.sender_name }}
                        {% else %}
                            <span>Anonymous</span>
                        {% endif %}
                        <span>| {{ m.date_time|date:"M, d, Y h:i A" }}</span>
                        
                    </div>
                    <p>{{ m.text }}</p>
                </div>
            {% endfor %}
        </div>

        <div>
            <form>
                <textarea id="chat-message-input" cols="50" rows="3" style="display: block;"></textarea>
                <input id="chat-message-submit" type="button" value="Send" class="btn btn-success">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="checkbox_anon">
                    <label class="form-check-label" id="checkbox_anon">
                        Anon
                    </label>
                </div>
            </form>
        </div>

        <a href="{% url 'chat:delayedmessage' topic_id %}"><button class="btn btn-secondary">Delayed Message</button></a>

        <a href="{% url 'chat:topic' %}"><button class="btn btn-secondary">Back to topics</button></a>
    </div>

    <div class="pagination" style="margin: 20px;">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?name=Planes&page=1">&laquo; first</a>
                <a href="?name=Planes&page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?name=Planes&page={{ page_obj.next_page_number }}">next</a>
                <a href="?name=Planes&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>


    <script>
        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/'
            + '{{ topic_id }}'
            + '/'
        );
        
        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data)['message'];

            const element = document.querySelector("#chat_messages");

            if (element.querySelectorAll('.number_div').length !== 5) {
                element.insertAdjacentHTML("beforeend",
                    `<div style="width: 450px; background-color: gray; margin: 20px;">
                        <div>
                            <span>${data['sender_name']}</span>
                            <span>| ${data['date_time']}</span>         
                        </div>
                        <p>${data['text']}</p>
                    </div>`
                );
            }
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input')
            const checkbox_anon = document.querySelector('#checkbox_anon').checked

            message = messageInputDom.value;

            chatSocket.send(JSON.stringify({
                'topic_id' : '{{ topic_id }}',
                'message': message,
                'checkbox_anon' : checkbox_anon,
            }));

            messageInputDom.value = '';
        };
    </script>
</body>
</html>